### ISSUE TITLE
may need to let some mutation happen during render

### ISSUE THREAD

**Issue by neonstalwart** [Raynos/mercury#72] opened 2014-07-24 21:22 UTC
this is a result of trying out #70 

i may have an issue with https://github.com/Raynos/main-loop/commit/33c28cfa309c6f7d5798a815e7baf04adeb45edb - in theory it's excellent, but in practice there could be some things which potentially cannot avoid mutating state during an update... i know - it's not good:exclamation: 

the first thing i've found that throws this error is for an open popup component that has a blur handler that is being invoked during a patch - patching nodes can cause a blur if the current active element is removed from the document and so my handler responds during a patch.  in the handler, i close the popup, which involves updating state, and hence the error is thrown.  i don't know that i can use a `setTimeout` to defer updating the state because this will break logic that depends on the sequencing of blur and corresponding focus events - this stuff is ugly but unavoidable when trying to respond to blur and focus events.

i think in this case i'll be able to ignore the blur event by checking if the node is in the document but that doesn't fix the issue where you might be doing something like preventing focus from moving when validating an input when it's blurred.

your suggestion in irc was possibly to allow mutation that has originated from dom-delegator

**Comment by kumavis** [comment] 2015-02-05 08:39
wow thats an interesting edge-case!

**Comment by kumavis** [comment] 2015-02-05 08:43
@neonstalwart so the problem is that it is firing an event registered for an element that no longer in the dom?

**Comment by neonstalwart** [comment] 2015-02-05 12:24
@kumavis the problem removing nodes is not the main point - that is something I've been able to mostly address in virtual-dom. the real problem you should give your attention to is that blur events fire synchronously and if you do something to shift focus during a render then your blur handler will be fired in the middle of a render. if your blur handler mutates state then an error will be thrown because you are not allowed to mutate state during a render. this is something which is actually quite common once you do anything that uses a blur handler.

**Comment by kumavis** [comment] 2015-02-05 18:33
gotcha!
i remember the ember core folks talking about having to invalidate renders.
i wonder if we could somehow fire blur handlers for to-be-removed elements after virtual render but before dom render...

so we would virtual render twice and dom render once

**Comment by neonstalwart** [comment] 2015-02-05 19:09
after talking more with @kumavis in irc, we came to realize that maybe we could ignore state mutations during the patch phase.  the error is really for the purpose of stopping people mutating state during render but this mutation is happening during patch.  @Raynos what do you think about changing main-loop so that `InvalidUpdateInRender` does not throw during the patch phase?

**Comment by Raynos** [comment] 2015-02-05 19:20
@neonstalwart 

We want to gaurd the patch phase to stop people doing naughty things in hooks and widgets.

Can we update dom-delegator to force blur into a next-tick ? Would that fix the problem ?

**Comment by neonstalwart** [comment] 2015-02-05 19:23
i don't think we can delay the event - then you can't prevent a blur. also, it's not uncommon for blur and focus logic to work together.  if you try to delay the events you'll probably introduce a whole slew of new problems worse than this one.

**Comment by kumavis** [comment] 2015-02-05 19:25
I would accept allowing state change during a patch as the lesser of evils

**Comment by Raynos** [comment] 2015-02-05 19:29
@kumavis @neonstalwart seems reasonable. However let's gaurd both tree creation & diff because of how thunks do lazy tree creation.

**Comment by kumavis** [comment] 2015-02-05 19:43
pending https://github.com/Raynos/main-loop/pull/15
and updating main-loop dep here

**Comment by Raynos** [comment] 2015-02-05 19:53
Fixed in latest mercury.

**Closed by Raynos** 2015-02-05 19:53 UTC
Labels: bug
